# Generated by Django 5.2.14 on 2026-08-08 05:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0006_city_maghrib_auto_congregation_enabled_and_more'),
        ('mosques', '0016_notificationjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousVisitor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_seen', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen', models.DateTimeField(auto_now=True, db_index=True)),
                ('visit_count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['first_seen', 'last_seen'], name='analytics_a_first_s_e81b94_idx')],
            },
        ),
        migrations.CreateModel(
            name='VisitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(db_index=True, default='page_view', max_length=50)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_events', to='locations.city')),
                ('mosque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_events', to='mosques.mosque')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='analytics.anonymousvisitor')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'city'], name='analytics_v_timesta_c3f18e_idx'), models.Index(fields=['visitor', 'timestamp'], name='analytics_v_visitor_008984_idx'), models.Index(fields=['event_type', 'timestamp'], name='analytics_v_event_t_499cf7_idx')],
            },
        ),
    ]
