"""Platform admin URL routes mapping."""

from django.urls import path

from apps.platform_admin.views import (
    SuperAdminDashboardStatsAPIView,
    SuperAdminLoginAPIView,
    SuperAdminRegistrationRequestListAPIView,
    SuperAdminRegistrationRequestDetailAPIView,
    SuperAdminRegistrationRequestApproveAPIView,
    SuperAdminRegistrationRequestRejectAPIView,
    SuperAdminMarkUnderVerificationAPIView,
    SuperAdminVerificationNotesAPIView,
    SuperAdminResetMosqueAdminPasswordAPIView,
    SuperAdminCityListCreateAPIView,
    SuperAdminCityDetailAPIView,
    SuperAdminCityTimetableAPIView,
    SuperAdminCityTimetableAcknowledgeAPIView,
    SuperAdminCityAdminListCreateAPIView,
    SuperAdminCityAdminDetailAPIView,
    SuperAdminCityAdminResetPasswordAPIView,
    SuperAdminCityAdminMobileChangeAPIView,
    SuperAdminCityAdminMobileVerifyAPIView,
    SuperAdminCityAdminAssignMosqueAPIView,
    SuperAdminMosqueListAPIView,
    SuperAdminMosqueStatusAPIView,
    SuperAdminMosqueDeleteAPIView,
    SuperAdminAccountRecoveryListAPIView,
    SuperAdminAccountRecoveryDetailAPIView,
    SuperAdminAccountRecoveryApproveAPIView,
    SuperAdminAccountRecoveryRejectAPIView,
    SuperAdminAccountRecoveryReopenAPIView,
)

urlpatterns = [
    path("auth/login/", SuperAdminLoginAPIView.as_view(), name="platform-admin-login"),
    path("dashboard/stats/", SuperAdminDashboardStatsAPIView.as_view(), name="platform-admin-stats"),
    path("requests/", SuperAdminRegistrationRequestListAPIView.as_view(), name="platform-admin-requests-list"),
    path("requests/<int:pk>/", SuperAdminRegistrationRequestDetailAPIView.as_view(), name="platform-admin-requests-detail"),
    path("requests/<int:pk>/approve/", SuperAdminRegistrationRequestApproveAPIView.as_view(), name="platform-admin-requests-approve"),
    path("requests/<int:pk>/reject/", SuperAdminRegistrationRequestRejectAPIView.as_view(), name="platform-admin-requests-reject"),
    path("requests/<int:pk>/mark-under-verification/", SuperAdminMarkUnderVerificationAPIView.as_view(), name="platform-admin-requests-under-verification"),
    path("requests/<int:pk>/verification-notes/", SuperAdminVerificationNotesAPIView.as_view(), name="platform-admin-requests-verification-notes"),
    path("requests/<int:pk>/reset-password/", SuperAdminResetMosqueAdminPasswordAPIView.as_view(), name="platform-admin-request-reset-password"),
    path("cities/", SuperAdminCityListCreateAPIView.as_view(), name="platform-admin-cities-list"),
    path("cities/<int:pk>/", SuperAdminCityDetailAPIView.as_view(), name="platform-admin-cities-detail"),
    path("cities/<int:pk>/timetables/<str:action>/", SuperAdminCityTimetableAPIView.as_view(), name="platform-admin-cities-timetables"),
    path("cities/<int:pk>/timetables-acknowledge/", SuperAdminCityTimetableAcknowledgeAPIView.as_view(), name="platform-admin-cities-timetables-acknowledge"),
    path("city-admins/", SuperAdminCityAdminListCreateAPIView.as_view(), name="platform-admin-city-admins-list"),
    path("city-admins/<int:pk>/", SuperAdminCityAdminDetailAPIView.as_view(), name="platform-admin-city-admins-detail"),
    path("city-admins/<int:pk>/reset-password/", SuperAdminCityAdminResetPasswordAPIView.as_view(), name="platform-admin-city-admins-reset-password"),
    path("city-admins/<int:pk>/change-mobile/", SuperAdminCityAdminMobileChangeAPIView.as_view(), name="platform-admin-city-admins-change-mobile"),
    path("city-admins/<int:pk>/verify-mobile/", SuperAdminCityAdminMobileVerifyAPIView.as_view(), name="platform-admin-city-admins-verify-mobile"),
    path("city-admins/<int:pk>/assign-mosque/", SuperAdminCityAdminAssignMosqueAPIView.as_view(), name="platform-admin-city-admins-assign-mosque"),
    path("mosques/", SuperAdminMosqueListAPIView.as_view(), name="platform-admin-mosques-list"),
    path("mosques/<int:pk>/status/", SuperAdminMosqueStatusAPIView.as_view(), name="platform-admin-mosques-status"),
    path("mosques/<int:pk>/", SuperAdminMosqueDeleteAPIView.as_view(), name="platform-admin-mosques-delete"),
    path("account-recovery/", SuperAdminAccountRecoveryListAPIView.as_view(), name="platform-admin-recovery-list"),
    path("account-recovery/<int:pk>/", SuperAdminAccountRecoveryDetailAPIView.as_view(), name="platform-admin-recovery-detail"),
    path("account-recovery/<int:pk>/approve/", SuperAdminAccountRecoveryApproveAPIView.as_view(), name="platform-admin-recovery-approve"),
    path("account-recovery/<int:pk>/reject/", SuperAdminAccountRecoveryRejectAPIView.as_view(), name="platform-admin-recovery-reject"),
    path("account-recovery/<int:pk>/reopen/", SuperAdminAccountRecoveryReopenAPIView.as_view(), name="platform-admin-recovery-reopen"),
]


