# Generated by Django 5.2.14 on 2026-07-02 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mosques', '0011_mosqueregistrationrequest_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MosqueApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=20)),
                ('registration_request_id', models.IntegerField(blank=True, null=True)),
                ('mosque_name', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_approval_logs', to=settings.AUTH_USER_MODEL)),
                ('mosque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_logs', to='mosques.mosque')),
            ],
            options={
                'db_table': 'platform_admin_mosqueapprovallog',
                'ordering': ['-created_at'],
            },
        ),
    ]
