# Generated by Django 5.2.14 on 2026-05-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MosqueRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mosque_name', models.CharField(max_length=255)),
                ('admin_name', models.CharField(blank=True, max_length=255)),
                ('mobile_number', models.CharField(max_length=32)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('address', models.TextField(blank=True)),
                ('google_maps_link', models.URLField(blank=True, max_length=500)),
                ('women_prayer_available', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'city'], name='mosques_mos_status_59cae7_idx'), models.Index(fields=['mosque_name', 'mobile_number', 'status'], name='mosques_mos_mosque__b6a38f_idx')],
            },
        ),
    ]
