# Generated by Django 5.2.14 on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mosques", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mosque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mosque_name", models.CharField(max_length=255)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("address", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("women_prayer_available", models.BooleanField(default=False)),
                (
                    "mosque_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["mosque_name"],
                "indexes": [
                    models.Index(
                        fields=["mosque_status", "city"],
                        name="mosques_mos_mosque__e9d343_idx",
                    ),
                    models.Index(
                        fields=["mosque_name", "city"],
                        name="mosques_mos_mosque__053a8f_idx",
                    ),
                ],
            },
        ),
    ]
