# Generated by Django 5.2.14 on 2026-06-01 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0002_mosque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mosque',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='mosque',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mosque',
            name='mosque_type',
            field=models.CharField(choices=[('jama_masjid', 'Jama Masjid (Juma Mosque)'), ('daily_prayer', 'Daily Prayer Hall'), ('musallah', 'Musallah (Prayer Room)')], default='jama_masjid', max_length=50),
        ),
        migrations.AddField(
            model_name='mosque',
            name='parking_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mosque',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='mosque_profiles/'),
        ),
        migrations.AddField(
            model_name='mosque',
            name='separate_women_entrance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mosque',
            name='website',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mosque',
            name='wheelchair_accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mosque',
            name='wudu_facility_available',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MosqueOperatingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('open_24_hours', models.BooleanField(default=False)),
                ('fajr_open', models.TimeField(blank=True, null=True)),
                ('fajr_close', models.TimeField(blank=True, null=True)),
                ('dhuhr_open', models.TimeField(blank=True, null=True)),
                ('dhuhr_close', models.TimeField(blank=True, null=True)),
                ('asr_open', models.TimeField(blank=True, null=True)),
                ('asr_close', models.TimeField(blank=True, null=True)),
                ('maghrib_open', models.TimeField(blank=True, null=True)),
                ('maghrib_close', models.TimeField(blank=True, null=True)),
                ('isha_open', models.TimeField(blank=True, null=True)),
                ('isha_close', models.TimeField(blank=True, null=True)),
                ('mosque', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operating_schedule', to='mosques.mosque')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_operating_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
