# Generated by Django 5.2.14 on 2026-06-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0003_mosque_contact_phone_mosque_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosque',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mosqueregistrationrequest',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
