# Generated by Django 5.2.14 on 2026-06-02 01:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0006_mosqueannouncement_mosqueevent_mosquephoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mosque',
            index=models.Index(fields=['latitude', 'longitude'], name='mosques_mos_latitud_687eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='mosqueannouncement',
            index=models.Index(fields=['is_active', 'status', 'start_date', 'end_date'], name='mosques_mos_is_acti_7aa88f_idx'),
        ),
        migrations.AddIndex(
            model_name='mosqueevent',
            index=models.Index(fields=['is_active', 'status', 'event_date'], name='mosques_mos_is_acti_b33260_idx'),
        ),
    ]
