# Generated by Django 5.2.14 on 2026-06-02 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0007_mosque_mosques_mos_latitud_687eb5_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule_type', models.CharField(choices=[('khutbah', 'Friday Khutbah Shift'), ('weekly_dars', 'Weekly Dars')], db_index=True, max_length=50)),
                ('event_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('speaker', models.CharField(max_length=255)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('extended_data', models.JSONField(blank=True, default=dict)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='mosques.mosque')),
            ],
            options={
                'ordering': ['event_date', 'start_time'],
                'indexes': [models.Index(fields=['mosque', 'schedule_type', 'event_date'], name='mosques_com_mosque__ef9ade_idx')],
            },
        ),
    ]
