# Generated by Django 5.2.14 on 2026-06-02 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_city_timezone'),
        ('mosques', '0008_communityschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosque',
            name='city_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mosques', to='locations.city'),
        ),
        migrations.AddField(
            model_name='mosqueregistrationrequest',
            name='city_raw',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='mosqueregistrationrequest',
            name='city_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_requests', to='locations.city'),
        ),
        migrations.AddIndex(
            model_name='mosque',
            index=models.Index(fields=['mosque_status', 'city_relation'], name='mosques_mos_mosque__8dc31e_idx'),
        ),
        migrations.AddIndex(
            model_name='mosque',
            index=models.Index(fields=['mosque_name', 'city_relation'], name='mosques_mos_mosque__81478e_idx'),
        ),
        migrations.AddIndex(
            model_name='mosqueregistrationrequest',
            index=models.Index(fields=['status', 'city_relation'], name='mosques_mos_status_49af3b_idx'),
        ),
    ]
