# Generated by Django 5.2.14 on 2026-07-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0011_mosqueregistrationrequest_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosque',
            name='community_hall_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mosque',
            name='contact_email',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='mosque',
            name='drinking_water_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mosque',
            name='eid_prayer_ground_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mosque',
            name='funeral_prayer_facility_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mosque',
            name='hifz_program_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mosque',
            name='imam_contact_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='mosque',
            name='imam_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mosque',
            name='library_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mosque',
            name='muslim_burial_ground_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mosque',
            name='nikah_service_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mosque',
            name='quran_classes_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mosque',
            name='ramadan_iftar_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mosque',
            name='washrooms_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mosque',
            name='zakat_collection_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mosqueregistrationrequest',
            name='email',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='mosqueregistrationrequest',
            name='imam_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mosqueregistrationrequest',
            name='mobile_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mosqueregistrationrequest',
            name='verification_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mosqueregistrationrequest',
            name='verification_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
