# Generated by Django 5.2.14 on 2026-07-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0012_sprint3_registration_and_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosqueregistrationrequest',
            name='whatsapp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mosqueregistrationrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('whatsapp_verified', 'WhatsApp Verified'), ('pending', 'Pending Review'), ('under_verification', 'Under Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=25),
        ),
    ]
