# Generated by Django 5.2.14 on 2026-07-03 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0013_mosqueregistrationrequest_whatsapp_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mosqueregistrationrequest',
            name='super_admin_notes',
            field=models.TextField(blank=True, help_text="Internal verification notes. Never visible publicly. E.g. 'Verified via WhatsApp call.'"),
        ),
        migrations.AddField(
            model_name='mosqueregistrationrequest',
            name='under_verification_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mosqueregistrationrequest',
            name='under_verification_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='under_verification_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mosqueregistrationrequest',
            name='whatsapp_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
