# Generated by Django 5.2.14 on 2026-07-03 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_city_acknowledged_timetable_year_and_more'),
        ('mosques', '0014_add_verification_timestamps_and_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosqueannouncement',
            name='announcement_type',
            field=models.CharField(choices=[('general', 'General'), ('ramadan', 'Ramadan'), ('eid', 'Eid'), ('prayer_change', 'Prayer Change'), ('emergency', 'Emergency'), ('weather', 'Weather'), ('community', 'Community'), ('charity', 'Charity'), ('education', 'Education'), ('lost_found', 'Lost & Found')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='mosqueannouncement',
            name='banner_image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mosqueannouncement',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='locations.city'),
        ),
        migrations.AddField(
            model_name='mosqueannouncement',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mosqueannouncement',
            name='short_summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mosqueevent',
            name='attachments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mosqueevent',
            name='banner',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mosqueevent',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='locations.city'),
        ),
        migrations.AddField(
            model_name='mosqueevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mosqueevent',
            name='max_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mosqueevent',
            name='registration_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mosqueannouncement',
            name='mosque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='mosques.mosque'),
        ),
        migrations.AlterField(
            model_name='mosqueevent',
            name='mosque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='mosques.mosque'),
        ),
    ]
