# Generated by Django 5.2.14 on 2026-07-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0015_mosqueannouncement_announcement_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.CharField(max_length=255)),
                ('channel', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
