# Generated by Django 5.2.14 on 2026-08-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0016_notificationjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosqueoperatingschedule',
            name='general_close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mosqueoperatingschedule',
            name='general_open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mosqueoperatingschedule',
            name='schedule_mode',
            field=models.CharField(choices=[('24_HOURS', '24 Hours'), ('SALAH_BASED', 'Salah-Based Schedule'), ('GENERAL', 'General Open-Close')], default='SALAH_BASED', max_length=20),
        ),
    ]
