# Generated by Django 5.2.14 on 2026-08-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0017_mosqueoperatingschedule_general_close_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosque',
            name='mosque_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', max_length=20),
        ),
    ]
