# Generated by Django 5.2.14 on 2026-08-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0018_alter_mosque_mosque_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosqueregistrationrequest',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='mosqueregistrationrequest',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
