# Generated by Django 5.2.14 on 2026-05-31 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mosques', '0002_mosque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fajr_time', models.TimeField()),
                ('dhuhr_time', models.TimeField()),
                ('asr_time', models.TimeField()),
                ('maghrib_time', models.TimeField()),
                ('isha_time', models.TimeField()),
                ('jumuah_time', models.TimeField()),
                ('effective_from', models.DateField()),
                ('mosque', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_timing', to='mosques.mosque')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_prayer_timings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['effective_from'], name='prayers_pra_effecti_7f56af_idx')],
            },
        ),
    ]
