# Generated by Django 5.2.14 on 2026-07-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayertiming',
            name='maghrib_congregation_mode',
            field=models.CharField(choices=[('manual', 'Manual Input'), ('city_offset', 'City Offset')], default='manual', max_length=20),
        ),
    ]
