# Generated by Django on 2026-08-12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0002_prayertiming_maghrib_congregation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayertiming',
            name='maghrib_delay_minutes',
            field=models.PositiveSmallIntegerField(
                default=15,
                help_text='Mosque-specific Jamaat delay in minutes after sunset (1-30 minutes). Applies ONLY to Maghrib.',
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ],
            ),
        ),
    ]
