# Generated by Django 5.2.14 on 2026-07-03 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mosqueadmin_additional_mosques_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mosqueadmin',
            name='additional_mosques',
        ),
    ]
