# Generated by Django 5.2.14 on 2026-07-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailverification_identityauditlog_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityauditlog',
            name='action',
            field=models.CharField(choices=[('otp_generated', 'OTP Generated'), ('otp_sent', 'OTP Sent'), ('otp_verified', 'OTP Verified'), ('otp_expired', 'OTP Expired'), ('otp_failed', 'OTP Failed'), ('email_sent', 'Email Sent'), ('email_verified', 'Email Verified'), ('password_changed', 'Password Changed'), ('password_reset', 'Password Reset'), ('password_reset_failed', 'Password Reset Failed'), ('temp_password_generated', 'Temporary Password Generated'), ('temp_password_reset', 'Temporary Password Reset'), ('login_failed', 'Login Failed'), ('login_locked', 'Login Locked'), ('registration_submitted', 'Registration Submitted'), ('under_verification', 'Under Verification'), ('verification_notes_updated', 'Verification Notes Updated'), ('registration_approved', 'Registration Approved'), ('registration_rejected', 'Registration Rejected'), ('account_recovery_requested', 'Account Recovery Requested'), ('first_login', 'First Login')], max_length=32),
        ),
    ]
