# Generated by Django 5.2.14 on 2026-08-10 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_identityauditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityauditlog',
            name='action',
            field=models.CharField(choices=[('otp_generated', 'OTP Generated'), ('otp_sent', 'OTP Sent'), ('otp_verified', 'OTP Verified'), ('otp_expired', 'OTP Expired'), ('otp_failed', 'OTP Failed'), ('email_sent', 'Email Sent'), ('email_verified', 'Email Verified'), ('password_changed', 'Password Changed'), ('password_reset', 'Password Reset'), ('password_reset_failed', 'Password Reset Failed'), ('temp_password_generated', 'Temporary Password Generated'), ('temp_password_reset', 'Temporary Password Reset'), ('login_failed', 'Login Failed'), ('login_locked', 'Login Locked'), ('registration_submitted', 'Registration Submitted'), ('under_verification', 'Under Verification'), ('verification_notes_updated', 'Verification Notes Updated'), ('registration_approved', 'Registration Approved'), ('registration_rejected', 'Registration Rejected'), ('account_recovery_requested', 'Account Recovery Requested'), ('account_recovery_approved', 'Account Recovery Approved'), ('account_recovery_rejected', 'Account Recovery Rejected'), ('first_login', 'First Login'), ('city_admin_created', 'City Admin Created'), ('city_admin_status_changed', 'City Admin Status Changed'), ('city_admin_mobile_changed', 'City Admin Mobile Changed'), ('city_admin_password_reset', 'City Admin Password Reset'), ('mosque_status_changed', 'Mosque Status Changed'), ('mosque_deleted', 'Mosque Deleted')], max_length=32),
        ),
        migrations.CreateModel(
            name='AccountRecoveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mosque_name', models.CharField(max_length=255)),
                ('applicant_name', models.CharField(max_length=255)),
                ('contact_email', models.CharField(blank=True, max_length=254)),
                ('contact_whatsapp', models.CharField(max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_recovery_requests', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_recovery_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
