# Generated by Django 5.2.14 on 2026-08-10 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_accountrecoveryrequest_reopened_at_and_more'),
        ('mosques', '0018_alter_mosque_mosque_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrecoveryrequest',
            name='mosque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_recovery_requests', to='mosques.mosque'),
        ),
    ]
