# Generated by Django 5.2.14 on 2026-08-12 02:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_accountrecoveryrequest_previous_registered_contact_and_more'),
        ('locations', '0006_city_maghrib_auto_congregation_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cityadmin',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('city',), name='unique_active_city_admin_per_city'),
        ),
    ]
