# Generated by Django 5.2.14 on 2026-06-02 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mosques', '0010_backfill_cities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JanazahNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('date_of_death', models.DateField()),
                ('salah_date', models.DateField()),
                ('salah_time', models.TimeField()),
                ('salah_details', models.TextField(blank=True)),
                ('burial_date', models.DateField(blank=True, null=True)),
                ('burial_time', models.TimeField(blank=True, null=True)),
                ('cemetery_name', models.CharField(blank=True, max_length=255)),
                ('cemetery_address', models.TextField(blank=True)),
                ('cemetery_gps_url', models.URLField(blank=True, max_length=500, null=True)),
                ('family_contact_name', models.CharField(blank=True, max_length=255)),
                ('family_contact_phone', models.CharField(blank=True, max_length=32)),
                ('publish_contact_info', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_janazahs', to=settings.AUTH_USER_MODEL)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='janazah_notices', to='mosques.mosque')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_janazahs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-salah_date', '-salah_time'],
                'indexes': [models.Index(fields=['status', 'salah_date'], name='community_s_status_bf8c21_idx'), models.Index(fields=['mosque', 'status'], name='community_s_mosque__6de19c_idx')],
            },
        ),
    ]
