# Generated by Django 5.2.14 on 2026-06-01 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_seed_default_cities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityCalendarImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('rows_processed', models.IntegerField()),
                ('rows_created', models.IntegerField()),
                ('rows_updated', models.IntegerField()),
                ('rows_skipped', models.IntegerField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_imports', to='locations.city')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CityDailyPrayerTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('fajr_time', models.TimeField()),
                ('sunrise_time', models.TimeField()),
                ('dhuhr_time', models.TimeField()),
                ('asr_time', models.TimeField()),
                ('maghrib_time', models.TimeField()),
                ('isha_time', models.TimeField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_prayer_timings', to='locations.city')),
            ],
            options={
                'ordering': ['date', 'city'],
                'indexes': [models.Index(fields=['city', 'date'], name='locations_c_city_id_5d173f_idx')],
                'unique_together': {('city', 'date')},
            },
        ),
    ]
