# Generated by Django 5.2.14 on 2026-07-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_city_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='acknowledged_timetable_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='timetable_policy',
            field=models.CharField(choices=[('ANNUAL_UPLOAD', 'Annual Upload Required'), ('CONTINUE_PREVIOUS', 'Continue Previous Timetable Until Replaced'), ('ASTRONOMICAL', 'Astronomical Calculation (Future)'), ('AUTHORITY', 'Official Authority Source (Future)')], default='ANNUAL_UPLOAD', max_length=30),
        ),
    ]
