# Generated by Django 5.2.14 on 2026-07-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_city_acknowledged_timetable_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='maghrib_auto_congregation_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='city',
            name='maghrib_congregation_offset',
            field=models.IntegerField(default=1),
        ),
    ]
